### ISSUE TITLE
No sound extraction

### ISSUE THREAD

**Issue by HappyMac3920** [spotlightishere/superbinary-parser#1]
When running main.py input output --extract-rofs, it expects one argument and fails to extract the firmware sounds.

**Comment by spotlightishere** [comment]
Implemented as of 6a838ef11f45ca629a6567b7e7f00aeb9ab08476! Please use it similar to the following:
```
python3 main.py FirmwareUpdate.uarp testing --decompress-fota --extract-rofs
```
